# Generated by Django 5.1.2 on 2024-10-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=128)),
                ('sheight', models.FloatField(max_length=128)),
                ('sage', models.FloatField(max_length=128)),
            ],
        ),
    ]
