# Generated by Django 5.1.2 on 2024-10-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApps1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sid',
            new_name='sno',
        ),
    ]
